ClubBiz/config/routes.rb
ClubBiz::Application.routes.draw do
  get "user/index"
  get "user/show"
  get '/user_details' => 'user#show', as: :show_user

  get "webapps/search" => 'webapps#search'
  get "webapps/about_us" => 'webapps#about_us'

  get "notification_objects/read" => 'notification_objects#read'
  get "notification_objects/unread" => 'notification_objects#unread'

  get "clubs/add_member"
  get "clubs/remove_member"
  get "clubs/like"
  get "clubs/unlike"
  get "clubs/invite"
  get "clubs/uninvite"
  get "clubs/accept_invite"
  get "clubs/add_admin"
  get "clubs/remove_admin"
  get 'clubs/:id/admin' => 'clubs#admin', as: :club_admin

  get "topics/subscribe"
  get "topics/unsubscribe"

  get "announcements/system_announcements" => 'announcements#system_announcements', as: :sys_ann

  get 'events/reserve_tickets' => 'events#reserve_tickets'
  get 'events/reserve_ticket'
  get "events/like"
  get "events/unlike"
  get "events/share"
  get "events/unshare"

  delete '/tickets/:id(.:format)' => 'tickets#destroy', as: :delete_ticket

  get 'browse/clubs', to: 'clubs#browse'
  get 'browse/events', to: 'events#browse'

  get "networks/:id/invite_clubs" => 'networks#invite_clubs', as: :invite
  get "networks/:id/share_events" => 'networks#share_events', as: :share_event

  resources :networks

  resources :tickets

  resources :office_holder_positions

  resources :announcements

  resources :posts

  resources :topics

  resources :discussion_forums

  resources :events

  resources :notifications

  resources :webapps

  devise_for :users

  resources :clubs

  root to: "webapps#index"
  get "/newsfeed" => "announcements#news_feed"

end

ClubBiz/app/models/announcement.rb
class Announcement < ActiveRecord::Base
	belongs_to :club
end

ClubBiz/app/models/club.rb
class Club < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader

	has_many :memberships
	has_many :users, through: :memberships
	has_many :events
	belongs_to :discussion_forum
	has_many :announcements
	has_many :office_holder_positions
	has_many :club_likes
	has_many :club_networks

	def is_current_admin(user_id)
		if Membership.exists?(user_id: user_id, club_id: id)
			if Membership.find_by(user_id: user_id, club_id: id).is_admin == 1
				return true
			else
				return false
			end
		else
			return false
		end
	end
end

ClubBiz/app/models/club_like.rb
class ClubLike < ActiveRecord::Base
	belongs_to :user
	belongs_to :club
end

ClubBiz/app/models/club_network.rb
class ClubNetwork < ActiveRecord::Base
	belongs_to :club
	belongs_to :network
end

ClubBiz/app/models/discussion_forum.rb
class DiscussionForum < ActiveRecord::Base
	has_many :topics
	has_one :club
	has_one :event
	has_one :network

	def belongs
		if Club.find_by(discussion_forum_id: id)
			return "club"
        elsif Event.find_by(discussion_forum_id: id)
        	return "event"
        else
        	return "network"
        end
    end

    def club(user_id)
    	if Club.find_by(discussion_forum_id: id)
			return Club.find_by(discussion_forum_id: id)
        elsif Event.find_by(discussion_forum_id: id)
        	event = Event.find_by(discussion_forum_id: id)
        	return Club.find_by(id: event.club_id)
        else
            network = Network.find_by(discussion_forum_id: id)
            ClubNetwork.where(network_id: network.id).each do |c|
                club = Club.find_by(id: c.club_id)
                if club.is_current_admin(user_id)
                   return club
                end
            end
        end
    end
end

ClubBiz/app/models/event.rb
class Event < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader
	mount_uploader :other_image_1, OtherImageUploader
	mount_uploader :other_image_2, OtherImageUploader
	mount_uploader :other_image_3, OtherImageUploader

	belongs_to :club
	belongs_to :discussion_forum
	has_many :tickets
	has_many :event_likes
	has_many :shared_events
end

ClubBiz/app/models/event_like.rb
class EventLike < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

ClubBiz/app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :club
end

ClubBiz/app/models/network.rb
class Network < ActiveRecord::Base
	has_many :club_networks
	belongs_to :discussion_forum
	has_many :shared_events
end

ClubBiz/app/models/notification.rb
class Notification < ActiveRecord::Base
	has_many :notifaction_objects
end

ClubBiz/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
end

ClubBiz/app/models/shared_event.rb
class SharedEvent < ActiveRecord::Base
	belongs_to :event
	belongs_to :network
end

ClubBiz/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
end

ClubBiz/app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

ClubBiz/app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :discussion_forum
	has_many :posts
	has_many :subscriptions
end

ClubBiz/app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :posts
  has_many :office_holder_positions
  has_many :tickets
  has_many :club_likes
  has_many :subscriptions
  has_many :event_likes
  has_many :notifcation_objects


  validates :first_name, format: { with: /\A[A-Z]\w+\z/, 	
	  message: "First name is incorrectly formatted!" }

  validates :last_name, format: { with: /\A[A-Z]\w+\z/, 	
	  message: "is incorrectly formatted!" }

  validates :phone_number, format: { with: /\A\+?\d+\z/, 	
	  message: "is incorrectly formatted!" }

  def full_name
    "#{first_name} #{last_name}"
  end

  def print_user_link
  end

end

ClubBiz/app/models/webapp.rb
class Webapp < ActiveRecord::Base
end

ClubBiz/app/controllers/discussion_forums_controller.rb
class DiscussionForumsController < ApplicationController
  before_action :set_discussion_forum, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /discussion_forums
  # GET /discussion_forums.json
  def index
    @discussion_forums = DiscussionForum.all
  end

  # GET /discussion_forums/1
  # GET /discussion_forums/1.json
  def show
    @topics = Topic.all
    @club = Club.find_by(id: params[:club_id])
  end

  # GET /discussion_forums/new
  def new
    @discussion_forum = DiscussionForum.new
  end

  # GET /discussion_forums/1/edit
  def edit
  end

  # POST /discussion_forums
  # POST /discussion_forums.json
  def create
    @discussion_forum = DiscussionForum.new(discussion_forum_params)

    respond_to do |format|
      if @discussion_forum.save
        format.html { redirect_to @discussion_forum, notice: 'Discussion forum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @discussion_forum }
      else
        format.html { render action: 'new' }
        format.json { render json: @discussion_forum.errors, status: :unprocessable_entity }
      end
    end
    return @discussion_forum.id
  end

  # PATCH/PUT /discussion_forums/1
  # PATCH/PUT /discussion_forums/1.json
  def update
    respond_to do |format|
      if @discussion_forum.update(discussion_forum_params)
        format.html { redirect_to @discussion_forum, notice: 'Discussion forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @discussion_forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussion_forums/1
  # DELETE /discussion_forums/1.json
  def destroy
    while Topic.exists?(discussion_forum_id: @discussion_forum.id) do
      Topic.find_by(discussion_forum_id: @discussion_forum.id).destroy
    end
    
    @discussion_forum.destroy
    respond_to do |format|
      format.html { redirect_to discussion_forums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion_forum
      @discussion_forum = DiscussionForum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_forum_params
      params[:discussion_forum]
    end
end

ClubBiz/app/helpers/clubs_helper.rb
module ClubsHelper
end

ClubBiz/app/helpers/discussion_forums_helper.rb
module DiscussionForumsHelper
end

ClubBiz/app/helpers/events_helper.rb
module EventsHelper
end

ClubBiz/app/helpers/posts_helper.rb
module PostsHelper
end

ClubBiz/app/helpers/user_helper.rb
module UserHelper
end

ClubBiz/app/views/discussion_forums/_form.html.erb
<%= form_for(@discussion_forum) do |f| %>
  <% if @discussion_forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion_forum.errors.count, "error") %> prohibited this discussion_forum from being saved:</h2>

      <ul>
      <% @discussion_forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ClubBiz/app/views/discussion_forums/edit.html.erb
<h1>Editing discussion_forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion_forum %> |
<%= link_to 'Back', discussion_forums_path %>

ClubBiz/app/views/discussion_forums/index.html.erb
<h1>Listing discussion_forums</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @discussion_forums.each do |discussion_forum| %>
      <tr>
        <td><%= link_to 'Show', discussion_forum %></td>
        <td><%= link_to 'Edit', edit_discussion_forum_path(discussion_forum) %></td>
        <td><%= link_to 'Destroy', discussion_forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion forum', new_discussion_forum_path %>

ClubBiz/app/views/discussion_forums/new.html.erb
<h1>New discussion_forum</h1>

<%= render 'form' %>

<%= link_to 'Back', discussion_forums_path %>

ClubBiz/app/views/discussion_forums/show.html.erb
<p>
  <ol class="breadcrumb">
    <li><%= link_to @club.name, @club %></li>
    <% if @discussion_forum.belongs == "event" %>
      <% event = Event.find_by(discussion_forum_id: @discussion_forum.id) %>
      <li><%= link_to 'Events', events_path(:club_id => @club.id) %></li>
      <li><%= link_to event.title, event %></li>
    <% end %>
    <li class="active">Discussion Forum</li>
  </ol>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Topics</h1></div>
  <div class="panel-footer"><%= link_to '+ New Topic', new_topic_path(:discussion_forum_id => @discussion_forum.id) %></div >
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @topics.each do |topic| %>
        	<% if topic.discussion_forum_id == @discussion_forum.id %>
  	      <tr>
  	        <td><%= link_to topic.title, topic_path(:id => topic.id, :club_id => @club.id) %></td>
            <td><%= topic.updated_at.strftime("%b %-d, %Y") %></td>
  	        <td>By <%= link_to User.find_by(id: topic.created_by).full_name, show_user_url(:user_id => topic.created_by) %><br>
  	        <%= topic.views %> Views
            <% if Subscription.find_by(user_id: current_user.id, topic_id: topic.id) %>
              <br><%= link_to({controller: "topics", action: 'unsubscribe', :topic_id => topic.id, method: :get}) do %>Following<% end %>
            <% else %>
              <br><%= link_to({controller: "topics", action: 'subscribe', :topic_id => topic.id, method: :get}) do %>Follow<% end %>
            <% end %>
            <% if @club.is_current_admin(current_user.id) %>
                  <br> <%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-default btn-xs" %> |
                    <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs" %>
            <% end %>
            </td>          
  	      </tr>
      	<% end %>
      <% end %>
    </tbody>
  </table>
  
</div>