ClubBiz/config/routes.rb
ClubBiz::Application.routes.draw do
  get "user/index"
  get "user/show"
  get '/user_details' => 'user#show', as: :show_user

  get "webapps/search" => 'webapps#search'
  get "webapps/about_us" => 'webapps#about_us'

  get "notification_objects/read" => 'notification_objects#read'
  get "notification_objects/unread" => 'notification_objects#unread'

  get "clubs/add_member"
  get "clubs/remove_member"
  get "clubs/like"
  get "clubs/unlike"
  get "clubs/invite"
  get "clubs/uninvite"
  get "clubs/accept_invite"
  get "clubs/add_admin"
  get "clubs/remove_admin"
  get 'clubs/:id/admin' => 'clubs#admin', as: :club_admin

  get "topics/subscribe"
  get "topics/unsubscribe"

  get "announcements/system_announcements" => 'announcements#system_announcements', as: :sys_ann

  get 'events/reserve_tickets' => 'events#reserve_tickets'
  get 'events/reserve_ticket'
  get "events/like"
  get "events/unlike"
  get "events/share"
  get "events/unshare"

  delete '/tickets/:id(.:format)' => 'tickets#destroy', as: :delete_ticket

  get 'browse/clubs', to: 'clubs#browse'
  get 'browse/events', to: 'events#browse'

  get "networks/:id/invite_clubs" => 'networks#invite_clubs', as: :invite
  get "networks/:id/share_events" => 'networks#share_events', as: :share_event

  resources :networks

  resources :tickets

  resources :office_holder_positions

  resources :announcements

  resources :posts

  resources :topics

  resources :discussion_forums

  resources :events

  resources :notifications

  resources :webapps

  devise_for :users

  resources :clubs

  root to: "webapps#index"
  get "/newsfeed" => "announcements#news_feed"

end

ClubBiz/app/models/announcement.rb
class Announcement < ActiveRecord::Base
	belongs_to :club
end

ClubBiz/app/models/club.rb
class Club < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader

	has_many :memberships
	has_many :users, through: :memberships
	has_many :events
	belongs_to :discussion_forum
	has_many :announcements
	has_many :office_holder_positions
	has_many :club_likes
	has_many :club_networks

	def is_current_admin(user_id)
		if Membership.exists?(user_id: user_id, club_id: id)
			if Membership.find_by(user_id: user_id, club_id: id).is_admin == 1
				return true
			else
				return false
			end
		else
			return false
		end
	end
end

ClubBiz/app/models/club_like.rb
class ClubLike < ActiveRecord::Base
	belongs_to :user
	belongs_to :club
end

ClubBiz/app/models/club_network.rb
class ClubNetwork < ActiveRecord::Base
	belongs_to :club
	belongs_to :network
end

ClubBiz/app/models/event.rb
class Event < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader
	mount_uploader :other_image_1, OtherImageUploader
	mount_uploader :other_image_2, OtherImageUploader
	mount_uploader :other_image_3, OtherImageUploader

	belongs_to :club
	belongs_to :discussion_forum
	has_many :tickets
	has_many :event_likes
	has_many :shared_events
end

ClubBiz/app/models/event_like.rb
class EventLike < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

ClubBiz/app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :club
end

ClubBiz/app/models/network.rb
class Network < ActiveRecord::Base
	has_many :club_networks
	belongs_to :discussion_forum
	has_many :shared_events
end

ClubBiz/app/models/notification.rb
class Notification < ActiveRecord::Base
	has_many :notifaction_objects
end

ClubBiz/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
end

ClubBiz/app/models/shared_event.rb
class SharedEvent < ActiveRecord::Base
	belongs_to :event
	belongs_to :network
end

ClubBiz/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
end

ClubBiz/app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

ClubBiz/app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :discussion_forum
	has_many :posts
	has_many :subscriptions
end

ClubBiz/app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :posts
  has_many :office_holder_positions
  has_many :tickets
  has_many :club_likes
  has_many :subscriptions
  has_many :event_likes
  has_many :notifcation_objects


  validates :first_name, format: { with: /\A[A-Z]\w+\z/, 	
	  message: "First name is incorrectly formatted!" }

  validates :last_name, format: { with: /\A[A-Z]\w+\z/, 	
	  message: "is incorrectly formatted!" }

  validates :phone_number, format: { with: /\A\+?\d+\z/, 	
	  message: "is incorrectly formatted!" }

  def full_name
    "#{first_name} #{last_name}"
  end

  def print_user_link
  end

end

ClubBiz/app/models/webapp.rb
class Webapp < ActiveRecord::Base
end

ClubBiz/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  helper_method :subscribe, :unsubscribe

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @posts = Post.all
    @topic.views += 1
    @topic.save
    @show_options = false

    @df = DiscussionForum.find_by(id: @topic.discussion_forum_id)
    @club = Club.find_by(id: params[:club_id])
    if @club.is_current_admin(current_user.id)
        @show_options = true
    end
    if @df.belongs == "event"
      @event = Event.find_by(discussion_forum_id: @df.id)
    elsif @df.belongs == "network"
      @network = Network.find_by(discussion_forum_id: @df.id)
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new()
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.created_by = current_user.id
    @topic.views = 0

    df_id = @topic.discussion_forum_id
    club = DiscussionForum.find_by(id: df_id).club(current_user.id)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_path(:id => @topic.id, :club_id => club.id), notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    df_id = @topic.discussion_forum_id
    club = DiscussionForum.find_by(id: df_id).club(current_user.id)

    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_path(:id => @topic.id, :club_id => club.id), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    # Delete all posts for this topic
    while Post.exists?(topic_id: @topic.id) do
      Post.find_by(topic_id: @topic.id).destroy
    end
    while Subscription.exists?(topic_id: @topic.id) do
      Subscription.find_by(topic_id: @topic.id).destroy
    end

    df_id = @topic.discussion_forum_id
    club = DiscussionForum.find_by(id: df_id).club(current_user.id)

    @topic.destroy
    respond_to do |format|
      format.html { redirect_to discussion_forum_path(:id => df_id, :club_id => club.id) }
      format.json { head :no_content }
    end
  end

  def subscribe
    Subscription.create(:user_id => current_user.id, :topic_id => params[:topic_id])
    redirect_to :back
  end

  def unsubscribe
    Subscription.find_by(user_id: current_user.id, :topic_id => params[:topic_id]).destroy
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :created_by, :views, :discussion_forum_id)
    end
end

ClubBiz/app/helpers/clubs_helper.rb
module ClubsHelper
end

ClubBiz/app/helpers/events_helper.rb
module EventsHelper
end

ClubBiz/app/helpers/posts_helper.rb
module PostsHelper
end

ClubBiz/app/helpers/tickets_helper.rb
module TicketsHelper
end

ClubBiz/app/helpers/topics_helper.rb
module TopicsHelper
end

ClubBiz/app/helpers/user_helper.rb
module UserHelper
end

ClubBiz/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter topic title" %>
  </div>

  <%= f.hidden_field :discussion_forum_id %>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default'%>
  </div>
<% end %>

ClubBiz/app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', "/discussion_forums/#{@topic.discussion_forum_id}" %>

ClubBiz/app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created by</th>
      <th>Views</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.created_by %></td>
        <td><%= topic.views %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

ClubBiz/app/views/topics/new.html.erb
<h1>New topic</h1>

<% @topic.discussion_forum_id = params[:discussion_forum_id] %>

<%= render 'form' %>

<%= link_to 'Cancel', :back, class: 'btn btn-default' %>

ClubBiz/app/views/topics/show.html.erb
<% cid = params[:club_id] %>

<p>
	<ol class="breadcrumb">
	  <li><%= link_to @club.name, @club %></li>
	  <% if @df.belongs == "event" %>
	    <li><%= link_to 'Events', events_path(:club_id => @club.id) %></li>
	    <li><%= link_to @event.title, @event %></li>
	  <% end %>
	  <% if @df.belongs == "network" %>
	  	<li><%= link_to 'Administration', club_admin_url(:id => @club.id) %></li>
	  	<li><%= link_to 'Networks', club_admin_url(:id => @club.id, :tab => "network") %></li>
	  	<li><%= link_to @network.name, network_url(:id => @network.id, :club_id => cid) %></li>
	  	<li><%= link_to 'Discussion Forum', network_path(:id => @network.id, :tab => "discussion", :club_id => cid) %></li>
	  <% else %>
	  	<li><%= link_to 'Discussion Forum', discussion_forum_path(:id => @df.id, :club_id => @club.id) %></li>
	  <% end %>
	  <li class="active"><%= @topic.title %></li>
	</ol>
</p>


<h1><%= @topic.title %></h1>
<p>
	<strong>Created by:</strong> 
	<%= link_to User.find_by(id: @topic.created_by).full_name, show_user_url(:user_id => @topic.created_by) %>
	on <%= @topic.created_at.strftime("%b %-d, %Y") %>
</p>
<p>
	<%= link_to 'New Post', new_post_path(:topic_id => @topic.id, :club_id => @club.id), class: "btn btn-default" %> 
	<% if Subscription.find_by(user_id: current_user.id, topic_id: @topic.id) %>
		<%= link_to({controller: "topics", action: 'unsubscribe', :topic_id => @topic.id, method: :get}, {class: "btn btn-default"}) do %>Following<% end %>
	<% else %>
		<%= link_to({controller: "topics", action: 'subscribe', :topic_id => @topic.id, method: :get}, {class: "btn btn-default"}) do %>Follow<% end %>
	<% end %>
	 <% if @show_options %>
            <%= link_to 'Edit', edit_topic_path(@topic), class: "btn btn-default" %>
            <%= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    <% end %>          
</p>

<div class="panel panel-default">
	<table class="table">
	  <tbody>
	    <% @posts.each do |post| %>
	    	<% if post.topic_id == @topic.id %>
		      <tr>
		      	<td>
		      		<strong><%= link_to User.find_by(id: post.user_id).full_name, show_user_url(:user_id => post.user_id) %></strong> 
		      		Posted on <%= post.created_at.strftime("%b %-d, %Y at %l:%M%P") %>
		        </td>
		        <% if @show_options %>
		        	<td><%= link_to 'X', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs" %></td>
		        <% end %>
		      </tr>
		      <tr>
		      	<td><%= post.content %></td>
		      </tr>
		    <% end %>
	    <% end %>
	  </tbody>
	</table>
</div>

<br>