ClubBiz/config/routes.rb
ClubBiz::Application.routes.draw do
  get "user/index"
  get "user/show"
  get '/user_details' => 'user#show', as: :show_user

  get "webapps/search" => 'webapps#search'
  get "webapps/about_us" => 'webapps#about_us'

  get "notification_objects/read" => 'notification_objects#read'
  get "notification_objects/unread" => 'notification_objects#unread'

  get "clubs/add_member"
  get "clubs/remove_member"
  get "clubs/like"
  get "clubs/unlike"
  get "clubs/invite"
  get "clubs/uninvite"
  get "clubs/accept_invite"
  get "clubs/add_admin"
  get "clubs/remove_admin"
  get 'clubs/:id/admin' => 'clubs#admin', as: :club_admin

  get "topics/subscribe"
  get "topics/unsubscribe"

  get "announcements/system_announcements" => 'announcements#system_announcements', as: :sys_ann

  get 'events/reserve_tickets' => 'events#reserve_tickets'
  get 'events/reserve_ticket'
  get "events/like"
  get "events/unlike"
  get "events/share"
  get "events/unshare"

  delete '/tickets/:id(.:format)' => 'tickets#destroy', as: :delete_ticket

  get 'browse/clubs', to: 'clubs#browse'
  get 'browse/events', to: 'events#browse'

  get "networks/:id/invite_clubs" => 'networks#invite_clubs', as: :invite
  get "networks/:id/share_events" => 'networks#share_events', as: :share_event

  resources :networks

  resources :tickets

  resources :office_holder_positions

  resources :announcements

  resources :posts

  resources :topics

  resources :discussion_forums

  resources :events

  resources :notifications

  resources :webapps

  devise_for :users

  resources :clubs

  root to: "webapps#index"
  get "/newsfeed" => "announcements#news_feed"

end

ClubBiz/app/models/event.rb
class Event < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader
	mount_uploader :other_image_1, OtherImageUploader
	mount_uploader :other_image_2, OtherImageUploader
	mount_uploader :other_image_3, OtherImageUploader

	belongs_to :club
	belongs_to :discussion_forum
	has_many :tickets
	has_many :event_likes
	has_many :shared_events
end

ClubBiz/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  helper_method :reserve_ticket, :like, :unlike, :share, :unshare

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def browse
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.current_tickets = @event.tickets_total
    @event.likes = 0

    df = DiscussionForum.create
    @event.discussion_forum_id = df.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

    # Create a notification that announces the new event
    club_link = url_for("events/#{@event.id}")
    msg = "The event \"#{@event.title}\" has been created by \"#{Club.find(@event.club_id).name}\"!"
    notification = Notification.create(:message=>msg, :source_id=>current_user.id, :link=>club_link)

    # Send the notification to all users in the club that created the event
    Membership.where(club_id: @event.club_id).each do |ms|
      NotificationObject.create(:user_id=>ms.user_id, :notification_id=>notification.id, :read_status=>0)
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    while EventLike.exists?(event_id: @event.id) do
      EventLike.find_by(event_id: @event.id).destroy
    end

    while Ticket.exists?(event_id: @event.id) do
      Ticket.find_by(event_id: @event.id).destroy
    end

    DiscussionForum.find_by(id: @event.discussion_forum_id).destroy

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def reserve_ticket
    event_id = params[:event_id]
    quantity = params[:quantity].to_i
    @event = Event.find_by(id: event_id)

    repeat = Array.new(quantity,0)
    count = 0
    repeat.each do |a|
      if @event.current_tickets > 0
        Ticket.create(:event_id => event_id, :user_id => current_user.id, :paid => 0)
        @event.current_tickets = @event.current_tickets.to_i - 1
        @event.save
        count += 1
      else
        break
      end
    end

    if count < quantity
      redirect_to "/events/#{event_id}", notice: "Successfully reserved #{count} tickets."
    else
      redirect_to "/events/#{event_id}", notice: "Successfully reserved all tickets."
    end
  end

  def like
    EventLike.create(:user_id => current_user.id, :event_id => params[:event_id])
    event = Event.find_by(id: params[:event_id])
    event.likes += 1
    event.save
    redirect_to :back
  end

  def unlike
    EventLike.find_by(user_id: current_user.id, event_id: params[:event_id]).destroy
    event = Event.find_by(id: params[:event_id])
    event.likes -= 1
    if event.likes < 0
      event.likes = 0
    end
    event.save
    redirect_to :back
  end

  def share
    SharedEvent.create(:event_id => params[:event_id], :network_id => params[:network_id])
    redirect_to :back
  end

  def unshare
    SharedEvent.find_by(event_id: params[:event_id], network_id: params[:network_id]).destroy
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :event_datetime, :end_datetime, :location, 
        :description, :ticket_price, :tickets_total, :current_tickets, :purchase_location, 
        :sold_from, :club_id, :discussion_forum_id, :ticket_quantity, :quantity, :likes,
        :banner_image, :banner_image_cache, :other_image_1, :other_image_1_cache,
        :other_image_2, :other_image_2_cache, :other_image_3, :other_image_3_cache)
    end
end

ClubBiz/app/helpers/events_helper.rb
module EventsHelper
end

ClubBiz/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:  'form-control', placeholder: "Enter title" %>
  </div>
  <div class="form-group">
    <%= f.label :date_and_time %><br>
    <%= f.datetime_select :event_datetime, order: [:day,:month,:year], use_short_month: true, class: '  form-control' %><br>
    <%= f.label :to %><br>
    <%= f.datetime_select :end_datetime, order: [:day,:month,:year], use_short_month: true %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class:  'form-control', placeholder: "Enter location" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:  'form-control', placeholder: "Enter event description" %>
  </div>
  <div class="form-group">
    <%= f.label :ticket_price %><br>
    <%= f.text_field :ticket_price, class:  'form-control', placeholder: "Enter ticket price" %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_tickets %><br>
    <%= f.number_field :tickets_total, class:  'form-control', placeholder: "Enter number of tickets" %>
  </div>
  <div class="form-group">
    <%= f.label :purchase_location %><br>
    <%= f.text_field :purchase_location, class:  'form-control', placeholder: "Enter purchase location" %>
  </div>
  <div class="form-group">
    <%= f.label :ticket_sold_from %><br>
    <%= f.date_select :sold_from, order: [:day,:month,:year], use_short_month: true %>
  </div>
  <%= f.hidden_field :club_id %>
  <div>
    <%= f.label :banner_image %>
    <%= f.file_field :banner_image %>
    <%= f.hidden_field :banner_image_cache %>
  </div>
  <br>
  <div>
    <%= f.label :other_image_1 %>
    <%= f.file_field :other_image_1 %>
    <%= f.hidden_field :other_image_1_cache %>

    <%= f.label :other_image_2 %>
    <%= f.file_field :other_image_2 %>
    <%= f.hidden_field :other_image_2_cache %>
  <div>
    <%= f.label :other_image_3 %>
    <%= f.file_field :other_image_3 %>
    <%= f.hidden_field :other_image_3_cache %>
  </div>
  <p class="help-block">Three other images will be shown in a slide </p>
  <br>
  <div class="actions">
    <%= f.submit 'Submit', :class => "btn btn-default" %>
  </div>
  </div>
<% end %>

ClubBiz/app/views/events/browse.html.erb
<h1>Browse events</h1>

<p>
  <form action="">
    <select id="club" name="club" onchange="this.form.submit()" class="form-control">
      <option value="">Browse by Club</option>
      <% memberships = Membership.where(user_id: current_user.id) %>
      <% clubs = [] %>
      <% memberships.each do |ms| %>
        <% clubs << Club.find_by(id: ms.club_id) %>
      <% end %>
      <% clubs.each do |club| %>
        <option value=<%= club.id %>><%= club.name %></option>
      <% end %>
    </select>
  </form>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= link_to "Show All", url_for(), class: "btn btn-default" %></div>
  <table class="table">
    <thead>
      <tr>
        <th>Event Name</th>
        <th>Host</th>
        <th>Date and Time</th>
        <th>Location</th>
        <th>Description</th>
        <th>Available Tickets</th>
      </tr>
    </thead>
      <% if params["club"] %>
        <% clubs_events = Event.where(club_id: params["club"]) %>
      <% else %>
        <% clubs_events = Event.all %>
      <% end %>
      <% clubs_events = clubs_events.order(:event_datetime) %>
      <% clubs_events.each do |event| %>
        <tr>
          <td>
            <strong>
              <%= link_to event.title, event %></strong>
          </td>
          <td>
             <strong><%= link_to Club.find_by(id: event.club_id).name, Club.find_by(id: event.club_id) %>
            </strong>
          </td>
          <td><%= event.event_datetime.strftime("%b %-d at %l:%M%P") %></td>
          <td><%= event.location %></td>
          <td><%= event.description %></td>
          <td><%= event.current_tickets %> tickets still available!</td>
        </tr>
      <% end %>
  </table>
</div>

<br>

ClubBiz/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @event %>

ClubBiz/app/views/events/index.html.erb
<% if params[:club_id] %>

  <% cid = params[:club_id].to_i %>

  <!-- Link path -->
  <p>
    <ol class="breadcrumb">
      <li><%= link_to Club.find_by(id: cid).name, Club.find_by(id: cid) %></li>
      <li class="active">Events</li>
    </ol>
  </p>

  <h1>Events</h1>
<% if Membership.find_by(club_id: params["club_id"], user_id: current_user.id) %>
     <% if Membership.find_by(club_id: params["club_id"], user_id: current_user.id).is_admin == 1 %>
       <div class="panel-footer"><%= link_to '+ New Event', new_event_path(:club_id => params[:club_id]) %></div>
     <% end %>
    <% end %>

  <div class="panel panel-default">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Time and Date</th>
          <th>Description</th>
          <th>Tickets Available</th>
        </tr>
      </thead>
        <% @events.reverse.each do |event| %>
          <% if event.club_id ==  cid %>
            <% if Membership.find_by(user_id: current_user.id, club_id: event.club_id) %>
              <tr>
                <td>
                  <strong>
                    <%= link_to Club.find_by(id: event.club_id).name, Club.find_by(id: event.club_id) %>: 
                    <%= link_to event.title, event %>
                  </strong>
                </td>
                <td><%= event.event_datetime.strftime("%b %-d at %l:%M%P") %> @ <%= event.location %></td>
                <td><%= event.description %></td>
                <td><%= event.current_tickets %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
    </table>
  </div>

<% else %>
  <h1>My Clubs' Events</h1>
  <div class="panel panel-default">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Host</th>
          <th>Time and Date</th>
          <th>Location</th>
          <th>Description</th>
          <th>Tickets Available</th>
        </tr>
      </thead>
        <% @events.reverse.each do |event| %>
          <% if Membership.find_by(user_id: current_user.id, club_id: event.club_id) %>
            <tr>
              <td>
                <strong> 
                  <%= link_to event.title, event %>
                </strong>
              </td>
              <td>
                <strong>
                  <%= link_to Club.find_by(id: event.club_id).name, Club.find_by(id: event.club_id) %>
                </strong>
               </td>
              <td><%= event.event_datetime.strftime("%b %-d at %l:%M%P") %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= event.current_tickets %></td>
            </tr>
          <% end %>
        <% end %>
    </table>
  </div>

<% end %>

<br>

ClubBiz/app/views/events/new.html.erb
<h1>New event</h1>

<% @event.club_id = params[:club_id] %>

<%= render 'form' %>

<%= link_to 'Cancel', events_path(:club_id => params[:club_id]), :class => "btn btn-default" %>

ClubBiz/app/views/events/reserve_tickets.html.erb
<% quantity = params[:ticket_quantity].to_i %>
<% event_id = params[:event_id].to_i %>

<p>Reserving <%= quantity %> tickets. Are you sure?</p>
<%= link_to({controller: "events", action: 'reserve_ticket', :event_id => event_id, :quantity => quantity, method: :get}) do %>Continue<% end %>
<%= link_to 'Back', "/events/#{event_id}" %>

ClubBiz/app/views/events/show.html.erb
<!-- Link path -->
<p>
  <ol class="breadcrumb">
    <li><%= link_to Club.find_by(id: @event.club_id).name, Club.find_by(id: @event.club_id) %></li>
    <li><%= link_to 'Events', events_path(:club_id => @event.club_id) %></li>
    <li class="active"><%= @event.title %></li>
  </ol>
</p>

<% if @event.event_datetime.strftime("%Y").to_i > DateTime.now.strftime("%Y").to_i ||
  @event.end_datetime.strftime("%Y").to_i > DateTime.now.strftime("%Y").to_i %>
  <% date_format = "%b %-d, %Y at %l:%M%P" %>
<% else %>
  <% date_format = "%b %-d at %l:%M%P" %>
<% end %>

<% if @event.banner_image.url.present? %>
  <div><%= image_tag "#{@event.banner_image.url}", class: 'banner' %></div>
<% end %>

<div class="event-title">
  <h1><%= @event.title %></h1>
</div>

<div class="event_like">
    <% if EventLike.find_by(user_id: current_user.id, event_id: @event.id) %>
      <%= link_to({controller: "events", action: 'unlike', :event_id => @event.id, method: :get}) do %>Unlike<% end %>
    <% else %>
      <%= link_to({controller: "events", action: 'like', :event_id => @event.id, method: :get}) do %>Like<% end %>
    <% end %>
    (<%= @event.likes %> likes)
</div>

<script>
$(function(){
  $('#eventCarousel').carousel({interval:5000});
});
</script>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <div class="event-slideshow">
      <div id="eventCarousel" class="carousel slide" data-interval="false">
        <ol class="carousel-indicators">
          <li data-target="#eventCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#eventCarousel" data-slide-to="1"></li>
          <li data-target="#eventCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
          <% if @event.other_image_1.url.present? %>
            <div class="active item">
              <%= image_tag "#{@event.other_image_1.url}", class: 'slideshow' %>
            </div>
          <% else %>
            <div class="active item">
              <%= image_tag "no_photo.png", class: 'slideshow' %>
            </div>
          <% end %>
          <% if @event.other_image_2.url.present? %>
            <div class="item">
              <%= image_tag "#{@event.other_image_2.url}", class: 'slideshow' %>
            </div>
          <% else %>
            <div class="item">
              <%= image_tag "no_photo.png", class: 'slideshow' %>
            </div>
          <% end %>
          <% if @event.other_image_3.url.present? %>
            <div class="item">
              <%= image_tag "#{@event.other_image_3.url}", class: 'slideshow' %>
            </div>
          <% else %>
            <div class="item">
              <%= image_tag "no_photo.png", class: 'slideshow' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-6">
    <p><strong>Hosted by: </strong><%= Club.find_by(id: @event.club_id).name %></p>
    <p>
    <hr><strong>When:</strong> <%= @event.event_datetime.strftime(date_format) %>
     - 
    <% if @event.end_datetime.to_date > @event.event_datetime.to_date %>
      <%= @event.end_datetime.strftime(date_format) %><hr>
    <% else %>
      <%= @event.end_datetime.strftime("%l:%M%P") %><hr>
    <% end %>
    </p>
    <p><strong>Where:</strong> <%= @event.location %><hr></p>
    <p><%= @event.description %><hr></p>
    <p><strong>Tickets: </strong>$<%= @event.ticket_price %> each</p>
    <% if @event.current_tickets == 0 %>
      <p>Unfortunately, there are no more tickets available :(</p>
    <% elsif Ticket.exists?(event_id: @event.id, user_id: current_user.id) &&
    Ticket.where(event_id: @event.id, user_id: current_user.id).count == 4 %>
      <p>You already have reserved the maximum number of tickets (4).</p>
    <% else %>
      <p>
        <form action="reserve_tickets" method="get">
          <select id="ticket_quantity" name="ticket_quantity">
            <option value="1" selected="selected">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
          </select>
          <input type="hidden" name="event_id" value="<%= "#{@event.id}" %>" />
          <input type="submit" value="Reserve Tickets"/>
        </form>
      </p>
      <p>
        (<%= @event.current_tickets %> out of <%= @event.tickets_total %> available, Max 4 per person)
      </p>
    <% end %> 
    <p>
      <strong>Sold at: </strong><%= @event.purchase_location %> 
      <strong>from</strong> <%= @event.sold_from.strftime("%b %-d") %><hr>
    </p>
    <% if Membership.find_by(user_id: current_user.id, club_id: @event.club_id).is_admin == 1 %>
      <p><%= link_to 'Reserved Tickets', tickets_path(:event_id => @event.id) %></p>
    <% end %>
    <p><%= link_to 'Discussion Forum', discussion_forum_path(:id => @event.discussion_forum_id, :club_id => @event.club_id) %></p>
    <% if Membership.find_by(user_id: current_user.id, club_id: @event.club_id).is_admin == 1 %>
      <p>
        <%= link_to 'Edit', edit_event_path(@event) %> | 
        <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
  </div>
</div>