ClubBiz/config/routes.rb
ClubBiz::Application.routes.draw do
  get "user/index"
  get "user/show"
  get '/user_details' => 'user#show', as: :show_user

  get "webapps/search" => 'webapps#search'
  get "webapps/about_us" => 'webapps#about_us'

  get "notification_objects/read" => 'notification_objects#read'
  get "notification_objects/unread" => 'notification_objects#unread'

  get "clubs/add_member"
  get "clubs/remove_member"
  get "clubs/like"
  get "clubs/unlike"
  get "clubs/invite"
  get "clubs/uninvite"
  get "clubs/accept_invite"
  get "clubs/add_admin"
  get "clubs/remove_admin"
  get 'clubs/:id/admin' => 'clubs#admin', as: :club_admin

  get "topics/subscribe"
  get "topics/unsubscribe"

  get "announcements/system_announcements" => 'announcements#system_announcements', as: :sys_ann

  get 'events/reserve_tickets' => 'events#reserve_tickets'
  get 'events/reserve_ticket'
  get "events/like"
  get "events/unlike"
  get "events/share"
  get "events/unshare"

  delete '/tickets/:id(.:format)' => 'tickets#destroy', as: :delete_ticket

  get 'browse/clubs', to: 'clubs#browse'
  get 'browse/events', to: 'events#browse'

  get "networks/:id/invite_clubs" => 'networks#invite_clubs', as: :invite
  get "networks/:id/share_events" => 'networks#share_events', as: :share_event

  resources :networks

  resources :tickets

  resources :office_holder_positions

  resources :announcements

  resources :posts

  resources :topics

  resources :discussion_forums

  resources :events

  resources :notifications

  resources :webapps

  devise_for :users

  resources :clubs

  root to: "webapps#index"
  get "/newsfeed" => "announcements#news_feed"

end

ClubBiz/app/models/announcement.rb
class Announcement < ActiveRecord::Base
	belongs_to :club
end

ClubBiz/app/models/club.rb
class Club < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader

	has_many :memberships
	has_many :users, through: :memberships
	has_many :events
	belongs_to :discussion_forum
	has_many :announcements
	has_many :office_holder_positions
	has_many :club_likes
	has_many :club_networks

	def is_current_admin(user_id)
		if Membership.exists?(user_id: user_id, club_id: id)
			if Membership.find_by(user_id: user_id, club_id: id).is_admin == 1
				return true
			else
				return false
			end
		else
			return false
		end
	end
end

ClubBiz/app/models/club_like.rb
class ClubLike < ActiveRecord::Base
	belongs_to :user
	belongs_to :club
end

ClubBiz/app/models/club_network.rb
class ClubNetwork < ActiveRecord::Base
	belongs_to :club
	belongs_to :network
end

ClubBiz/app/models/event.rb
class Event < ActiveRecord::Base

	mount_uploader :banner_image, BannerImageUploader
	mount_uploader :other_image_1, OtherImageUploader
	mount_uploader :other_image_2, OtherImageUploader
	mount_uploader :other_image_3, OtherImageUploader

	belongs_to :club
	belongs_to :discussion_forum
	has_many :tickets
	has_many :event_likes
	has_many :shared_events
end

ClubBiz/app/models/event_like.rb
class EventLike < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

ClubBiz/app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :club
end

ClubBiz/app/models/network.rb
class Network < ActiveRecord::Base
	has_many :club_networks
	belongs_to :discussion_forum
	has_many :shared_events
end

ClubBiz/app/models/notification.rb
class Notification < ActiveRecord::Base
	has_many :notifaction_objects
end

ClubBiz/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
end

ClubBiz/app/models/shared_event.rb
class SharedEvent < ActiveRecord::Base
	belongs_to :event
	belongs_to :network
end

ClubBiz/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
end

ClubBiz/app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

ClubBiz/app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :discussion_forum
	has_many :posts
	has_many :subscriptions
end

ClubBiz/app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :posts
  has_many :office_holder_positions
  has_many :tickets
  has_many :club_likes
  has_many :subscriptions
  has_many :event_likes
  has_many :notifcation_objects


  validates :first_name, format: { with: /\A[A-Z]\w+\z/, 	
	  message: "First name is incorrectly formatted!" }

  validates :last_name, format: { with: /\A[A-Z]\w+\z/, 	
	  message: "is incorrectly formatted!" }

  validates :phone_number, format: { with: /\A\+?\d+\z/, 	
	  message: "is incorrectly formatted!" }

  def full_name
    "#{first_name} #{last_name}"
  end

  def print_user_link
  end

end

ClubBiz/app/models/webapp.rb
class Webapp < ActiveRecord::Base
end

ClubBiz/app/helpers/clubs_helper.rb
module ClubsHelper
end

ClubBiz/app/helpers/events_helper.rb
module EventsHelper
end

ClubBiz/app/helpers/posts_helper.rb
module PostsHelper
end

ClubBiz/app/helpers/user_helper.rb
module UserHelper
end

ClubBiz/app/views/layouts/application.html.erb
<!DOCTYPE html>	
<html>	
<head>	
 <title>ClubBiz</title>	
 <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>	
 <%= javascript_include_tag "application", "data-turbolinks-track" => true %>	
 <%= csrf_meta_tags %>
</head>	
<body>	
	 <div class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">	
	 	<div class="container">
		 	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-links">
		 		<span class="sr-only">Toggle navigation</span>
		 		<span class="icon-bar"></span>
		 		<span class="icon-bar"></span>
		 		<span class="icon-bar"></span>
		 	</button>

			 <%= link_to "Club Biz", webapps_path, class: 'navbar-brand' %>	
			 <div class="collapse navbar-collapse" id="navbar-links">
			 	<% if user_signed_in? %>
			 		<form action="/webapps/search" class="navbar-form navbar-left" role="search">
		        		<div class="form-group">
		          			<input id="search" type="text" class="form-control"
		          			placeholder="Search for clubs and events" name="search_term">
		        		</div>
		        		<button type="submit" class="btn btn-default">Search</button>
		      		</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<%= link_to("/notifications") do %>
								<% unreadnotif = NotificationObject.where(user_id: current_user.id, read_status: 0).count %>
								<span class="glyphicon glyphicon-globe notification-menu-item" id="notif"  onclick="myFunction()">
								<div class="badge"><%= unreadnotif %></div></span>
							<% end %>
						</li>
						<li class="dropdown">
			 				<a class="dropdown-toggle" data-toggle="dropdown">
			 				<%= "Hello, " + current_user.first_name %> 
			 				<b class="caret"></b></a>
		 					<ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
		 						<li><%= link_to "News Feed", "/newsfeed" %></li>
		 						<% if current_user.id == Webapp.first.university_admin %>
		 						<li><%= link_to "System Announcements", sys_ann_url %></li>
		 						<% end %>
		 						<li class="divider"></li>
		 						<li id="club-submenu" class="dropdown-submenu">
		 						<a href="/clubs">My Clubs</a>
			 					<ul class="dropdown-menu">
		 							<li class="dropdown-header">Admin</li>
		 							<% admin_ms = Membership.where(is_admin: 1, user_id: current_user.id) %>
		 							<% admin_clubs = [] %>
		 							<% counter = 0 %>
		 							<% admin_ms.each do |ms| %>
		 								<% admin_clubs << Club.find_by(id: ms.club_id) %>
		 							<% end %>
		 							<% admin_clubs.each do |club| %>
		 								<% if counter >= 3 %>
		 									<li><%= link_to "More...", "/clubs" %></li>
		 									<% break %>
		 								<% else %>
		 									<li><%= link_to club.name, "/clubs/#{club.id}" %></li>
		 									<% counter = counter + 1 %>
		 								<% end %>
		 							<% end %>
			 						<li class="dropdown-header"><%= "Member" %></li>
			 						<% member_ms = Membership.where(is_admin: 0, user_id: current_user.id) %>
		 							<% member_clubs = [] %>
		 							<% counter = 0 %>
		 							<% member_ms.each do |ms| %>
		 								<% member_clubs << Club.find_by(id: ms.club_id) %>
		 							<% end %>
		 							<% member_clubs.each do |club| %>
		 								<% if counter >= 3 %>
		 									<li><%= link_to "More...", "/clubs" %></li>
		 									<% break %>
		 								<% else %>
		 									<li><%= link_to club.name, "/clubs/#{club.id}" %></li>
		 									<% counter = counter + 1 %>
	 									<% end %>
		 							<% end %>
			 						<li class="divider"></li>
			 						<li><%= link_to "Register a Club", "/clubs/new" %></li>
			 					</ul>
			 					</li>
			 					<li class="dropdown-submenu">
		 						<a href="/events">My Events</a>
			 					<ul class="dropdown-menu">
		 							<li class="dropdown-header"><%= "Club Events" %></li>
			 						<% memberships = Membership.where(user_id: current_user.id) %>
			 						<% events = [] %>
			 						<% counter = 0 %>
			 						<% memberships.each do |ms| %>
			 							<% a_club_event = Event.where(club_id: ms.club_id) %>
			 							<% a_club_event.each do |event| %>
			 								<% events << event %>
		 								<% end %>
	 								<% end %>
	 								<% events.each do |event| %>
	 									<% if counter >= 3 %>
		 									<li><%= link_to "More...", "/clubs" %></li>
		 									<% break %>
		 								<% else %>
	 										<li><%= link_to event.title, "/events/#{event.id}" %></li>
	 										<% counter = counter + 1 %>
	 									<% end %>
									<% end %>
			 					</ul>
			 					</li>
			 					<li><%= link_to 'My Tickets', tickets_path %></li>
			 					<li class="divider"></li>
		 						<li><%= link_to "My Details", show_user_url(:user_id => current_user.id) %></li>
		 						<li><%= link_to "Edit Details", edit_user_registration_path %></li>
		 						<li class="divider"></li>
		 						<li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
	 						</ul>
			 			</li> 
					</ul>
					<ul class="nav navbar-nav navbar-left">
			 			<li class="dropdown">
			 				<%= link_to "Clubs", "/browse/clubs" %>
			 			</li>
			 			<li class="dropdown">
			 				<%= link_to "Events", "/browse/events" %>
			 			</li>
			 		</ul>
				<% else %>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Log in", new_user_session_path %></li>
					 	<li><%= link_to "Register", new_user_registration_path %></li>	
				 	</ul>
				<% end %>
			</div>
		 </div>	
	 </div>	
	 <div class="container">
	 	 <br>
	 	 <br>
	 	 <br>
	 	 <%= yield %>
	 	 <p class="notice"><%= notice %></p>
		 <p class="alert"><%= alert %></p>
	 </div>
	 <hr class="footer">
 	<div id="footer">
 		<%= link_to "About Us", "/webapps/about_us" %>
 	</div>
</body>	
</html>	